spring:
  application:
    name: service-desk-api

  profiles:
    active: dev

  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

info:
  app:
    name: Service Desk API
    description: API para gestão de chamados
    version: 1.0.0